imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%dev_database_driver%"
        host:     "%dev_database_host%"
        port:     "%dev_database_port%"
        dbname:   "%dev_database_name%"
        user:     "%dev_database_user%"
        password: "%dev_database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
