services:
    sbts.issue.issue_manager:
        class: Sbts\Bundle\IssueBundle\Model\IssueManager
        arguments: [@doctrine.orm.entity_manager]

    sbts.issue.form.issue:
        class: Sbts\Bundle\IssueBundle\Form\Type\IssueFormType
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: sbts_issue_form }

    bts.issue.form.subtask:
        class: Sbts\Bundle\IssueBundle\Form\Type\SubTaskFormType
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: sbts_issue_subtask_form }

    sbts.issue.security.voter:
        class:      Sbts\Bundle\IssueBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
            - { name: security.voter }

    sbts.issue.lifecycle.event_listener:
        class:  Sbts\Bundle\IssueBundle\EventListener\IssueLifecycleListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    sbts.activity.lifecycle.event_listener:
        class:  Sbts\Bundle\IssueBundle\EventListener\ActivityLifecycleListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: postPersist }
