<?php

namespace Sbts\Bundle\IssueBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    /**
     * @param string $code
     *
     * @return Issue
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function findByCode($code)
    {
        $codeParts = explode('-', $code);
        $id = (int) end($codeParts);

        return $this
            ->getEntityManager()
            ->createQuery('SELECT issue FROM SbtsIssueBundle:Issue issue WHERE issue.id = :id')
            ->setParameters([
                'id' => $id
            ])
            ->getSingleResult();
    }
}
