<?php

namespace Sbts\Bundle\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * @param string $code project code
     * @return Project
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByCode($code)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT projects FROM SbtsProjectBundle:Project projects WHERE projects.code = :code')
            ->setParameters(array(
                'code' => $code
            ))
            ->getSingleResult();
    }
}
